--PIVOT
/*
    Use PIVOT to re-orient a rowset by generating mulitple columns from values in a single column.
    Use UNPIVOT to re-orient mulitple columns in a an existing rowset into a single column.
*/
SELECT * FROM 
(
	SELECT P.PRODUCTID,PC.NAME,ISNULL(P.COLOR,'UnColored') AS COLOR
	FROM SALESLT.PRODUCTCATEGORY AS PC
	JOIN SALESLT.PRODUCT AS P
	ON PC.PRODUCTCATEGORYID=P.PRODUCTCATEGORYID
) AS PPC
PIVOT(COUNT(PRODUCTID) FOR COLOR IN ([RED],[BLUE],[BLACK],[SILVER],[YELLOW],[GREY],[MULTI],[UNCOLORED]))  PV
ORDER BY NAME

CREATE TABLE #PRODUCTCOLORPIVOT
(NAME VARCHAR(50),RED INT,BLUE INT,BLACK INT,SILVER INT,YELLOW INT,GREY INT,MULTI INT,UNCOLORED INT)

INSERT INTO #PRODUCTCOLORPIVOT
SELECT * FROM 
(
	SELECT P.PRODUCTID,PC.NAME,ISNULL(P.COLOR,'UnColored') AS COLOR
	FROM SALESLT.PRODUCTCATEGORY AS PC
	JOIN SALESLT.PRODUCT AS P
	ON PC.PRODUCTCATEGORYID=P.PRODUCTCATEGORYID
) AS PPC
PIVOT(COUNT(PRODUCTID) FOR COLOR IN ([RED],[BLUE],[BLACK],[SILVER],[YELLOW],[GREY],[MULTI],[UNCOLORED]))  PV
ORDER BY NAME

SELECT * FROM #PRODUCTCOLORPIVOT

---- UNPIVOT
SELECT NAME,COLOR,PRODUCTCOUNT
FROM
(
	SELECT NAME,
	[RED],[BLUE],[BLACK],[SILVER],[YELLOW],[GREY],[MULTI],[UNCOLORED]
	FROM #PRODUCTCOLORPIVOT 
)PCP
UNPIVOT
(
	PRODUCTCOUNT FOR COLOR IN ([RED],[BLUE],[BLACK],[SILVER],[YELLOW],[GREY],[MULTI],[UNCOLORED])
) AS PRODUCTCOUNT