
-- UNION
SELECT EMPLOYEENAME, 'LASTNAME'
FROM SALESLT.EMPLOYEE
UNION
SELECT FIRSTNAME, LASTNAME
FROM SALESLT.CUSTOMER
ORDER BY EMPLOYEENAME

--INTERSECT  -> RETURNS DATA WHICH ARE COMMON TO BOTH TABLES
SELECT EMPLOYEENAME, 'LASTNAME'
FROM SALESLT.EMPLOYEE
INTERSECT
SELECT FIRSTNAME, LASTNAME
FROM SALESLT.CUSTOMER
ORDER BY EMPLOYEENAME