use [AdventureWorksLT]

--cast
SELECT CAST(PRODUCTID AS VARCHAR(5)) + ':'+ NAME AS PRODUCTNAME
FROM SALESLT.PRODUCT

--CONVERT
SELECT CONVERT(VARCHAR(5),PRODUCTID) + ':'+ NAME AS PRODUCTNAME
FROM SALESLT.PRODUCT

--CONVERT DATES.  Selected values are in string/text
SELECT SELLSTARTDATE, CONVERT(VARCHAR(30),SELLSTARTDATE) AS CONVERTED_DATE,CONVERT(VARCHAR(30),SELLSTARTDATE,126) AS ISODATE
FROM SALESLT.PRODUCT

--TRY TO CAST
SELECT NAME ,TRY_CAST(SIZE AS INTEGER) AS NUMERICSIZE
FROM SALESLT.PRODUCT