use [AdventureWorksLT]

--null NUMBER=0
SELECT NAME ,ISNULL( TRY_CAST(SIZE AS INTEGER),0) AS NUMERICSIZE
FROM SALESLT.PRODUCT

--NULL STRING=LANK STRING
SELECT PRODUCTNUMBER, ISNULL(COLOR,'')+','+ISNULL(SIZE,'') AS PRODUCTDETAILS	
FROM SALESLT.PRODUCT

--MULTI COLOR=NULL
SELECT NAME, NULLIF(COLOR,'MULTI') AS SINGLECOLOR	
FROM SALESLT.PRODUCT

--FIND FIRST NON NULL DATE
SELECT NAME,COALESCE(DISCONTINUEDDATE,SELLSTARTDATE,SELLENDDATE) AS LAST_ACTIVITY
FROM SALESLT.PRODUCT	

--SEARCH  CASE
SELECT NAME,
	CASE
		WHEN SELLENDDATE IS NULL THEN 'ON SALE'
		--WHEN [WEIGHT] IS NULL THEN 'TO START'
		ELSE 'DISCONTINUED'
	END AS SALES_STATUS
FROM SALESLT.PRODUCT	

--SIMPLE CASE
SELECT NAME,
		CASE SIZE
			WHEN 'S' THEN 'SMALL'
			WHEN 'M' THEN 'MEDIUM'
			WHEN 'L' THEN 'LARGE'
			WHEN 'XL' THEN 'EXTRA-LARGE'
			ELSE ISNULL(SIZE,'N/A')
		END AS PRODUCT_SIZE
FROM SALESLT.PRODUCT	



