--RAISING ERROR---

	INSERT INTO SALESLT.SALESORDERDETAIL(SALESORDERID,ORDERQTY,PRODUCTID,UNITPRICE,UNITPRICEDISCOUNT)
	VALUES(100000,1,680,1431.50,0.0)

	UPDATE SALESLT.PRODUCT
	SET DISCONTINUEDDATE=GETDATE()
	WHERE PRODUCTID=0

	IF @@ROWCOUNT < 1
		RAISERROR('NO PRODUCT FOUND',16,0)

	IF @@ROWCOUNT < 1
		THROW 50001,'PRODUCT NOT FOUND',0;

BEGIN TRY
	UPDATE SALESLT.PRODUCT
	SET PRODUCTNUMBER=PRODUCTID/ISNULL(WEIGHT,0);
END TRY
BEGIN CATCH
	PRINT 'THE FOLLOWING ERROR OCCURED';
	PRINT ERROR_MESSAGE();
END CATCH

BEGIN TRY
	UPDATE SALESLT.PRODUCT
	SET PRODUCTNUMBER=PRODUCTID/ISNULL(WEIGHT,0);
END TRY
BEGIN CATCH
	PRINT 'THE FOLLOWING ERROR OCCURED';
	PRINT ERROR_MESSAGE();
	THROW;
END CATCH


BEGIN TRY
	UPDATE SALESLT.PRODUCT
	SET PRODUCTNUMBER=PRODUCTID/ISNULL(WEIGHT,0);
END TRY
BEGIN CATCH
	DECLARE @ERRORLOGID AS INT,@ERRORMSG AS VARCHAR(250);
	EXECUTE dbo.uspLogError @ERRORLOGID OUTPUT;
	SET @ERRORMSG='UPDATE FAILED DUE TO AN ERROR. ERROR IS #'
					+CAST(@ERRORLOGID AS VARCHAR);
	THROW 50001, @ERRORMSG,0;

END CATCH

SELECT * FROM DBO.ERRORLOG