


UPDATE SALESLT.PRODUCT
SET DiscontinuedDate=GETDATE()
WHERE PRODUCTID=6800;

IF @@ROWCOUNT<1
BEGIN
	PRINT 'PRODUCT WAS NOT FOUNT'
END
ELSE
BEGIN
	PRINT 'PRODUCT UPDATED';
END

--WHILE
DECLARE @CUSTID INT =1, @LNAME NVARCHAR(20);
WHILE @CUSTID<5
BEGIN
	SELECT @LNAME=LASTNAME FROM SALESLT.CUSTOMER
	WHERE CUSTOMERID=@CUSTID
	PRINT @LNAME;
	SET @CUSTID +=1;
END