--UPDATE

UPDATE SALESLT.CALLLOG
SET NOTES='NO NOTES'
WHERE NOTES IS NULL

select * from SALESLT.CallLog 

UPDATE SALESLT.CALLLOG
SET SalesPerson='' , PHONENUMBER = ''


-- UPDATE DATA FROM EXISTING TABLE
UPDATE SALESLT.CALLLOG
SET SalesPerson=C.SALESPERSON , PHONENUMBER = C.PHONE
FROM SALESLT.CUSTOMER AS C
WHERE C.CUSTOMERID=SALESLT.CALLLOG.CUSTOMERID

DELETE FROM SALESLT.CALLLOG 
WHERE CALLTIME < DATEADD(dd,-1,getdate())

truncate table saleslt.calllog


