--AGREGATE FUNCTIONS

SELECT COUNT(*) AS PRODUCTS, COUNT(DISTINCT PRODUCTCATEGORYID) AS CATEGORIES, AVG(LISTPRICE) AS AVGPRICE
FROM SALESLT.PRODUCT


SELECT COUNT(P.PRODUCTID) AS BIKEMODEL, AVG(P.LISTPRICE) AS AVGPRICE
FROM SALESLT.PRODUCT AS P
JOIN SALESLT.PRODUCTCATEGORY AS C
ON P.PRODUCTCATEGORYID=C.PRODUCTCATEGORYID
WHERE C.NAME LIKE '%Bikes'

