--GROUP BY
SELECT C.SALESPERSON, ISNULL(SUM(OH.SUBTOTAL),0.0) AS SALESREVENUE
FROM SALESLT.CUSTOMER C
LEFT JOIN SALESLT.SALESORDERHEADER OH
ON C.CUSTOMERID=OH.CUSTOMERID
GROUP BY C.SALESPERSON
ORDER BY SALESREVENUE DESC


SELECT C.SALESPERSON, CONCAT(C.FIRSTNAME,' ',C.LASTNAME) AS CUSTOMER, ISNULL(SUM(OH.SUBTOTAL),0.0) AS SALESREVENUE
FROM SALESLT.CUSTOMER C
LEFT JOIN SALESLT.SALESORDERHEADER OH
ON C.CUSTOMERID=OH.CUSTOMERID
GROUP BY C.SALESPERSON,CONCAT(C.FIRSTNAME,' ',C.LASTNAME)
ORDER BY SALESREVENUE DESC