--LOGICAL FUNCTIONS
SELECT NAME,SIZE AS NUMERIC_SIZE
FROM SALESLT.PRODUCT
WHERE ISNUMERIC(SIZE)=1

--IF ISNUMERIC IS TRUE THEN 'NUMERIC' ELSE 'NON NUMERIC'
SELECT NAME,IIF(ISNUMERIC(SIZE)=1 ,'NUMERIC','NON-NUMERIC') AS PRODUCTTYPE
FROM SALESLT.PRODUCT

--CHOOSE 'BIKE,COMPONENT,CLOTHING,ACCESORIES' BASED ON THE PARENTPRODUCTCATEGORYID
SELECT CAT.PARENTPRODUCTCATEGORYID,PROD.NAME AS PROD_NAME, CAT.NAME AS CATEG_NAME,
		CHOOSE(CAT.PARENTPRODUCTCATEGORYID ,'BIKE','COMPONENT','CLOTHING','ACCESSORIES') AS PRODUCT_TYPES
FROM SALESLT.PRODUCT AS PROD
JOIN SALESLT.PRODUCTCATEGORY AS CAT
ON PROD.PRODUCTCATEGORYID=CAT.PRODUCTCATEGORYID

