

SELECT YEAR(SELLSTARTDATE) AS STARTDATE,PRODUCTID, NAME
FROM SALESLT.PRODUCT
ORDER BY STARTDATE


SELECT YEAR(SELLSTARTDATE) AS STARTDATE,DATENAME(mm,SELLSTARTDATE) STARTMONTH,
		DAY(SELLSTARTDATE) AS STARTDAY, DATENAME(dw,SELLSTARTDATE) STARTWEEKDAY,
		PRODUCTID, NAME
FROM SALESLT.PRODUCT
ORDER BY STARTDATE

SELECT DATEDIFF(yy,SELLSTARTDATE,GETDATE()) YEARSOLD,PRODUCTID,NAME
FROM SALESLT.PRODUCT
ORDER BY PRODUCTID

SELECT UPPER(NAME) AS PRODUCTNAME
FROM SALESLT.PRODUCT

--STRING CONCAT
SELECT CONCAT(FIRSTNAME,' ',LASTNAME) AS FULLNAME
FROM SALESLT.CUSTOMER

--GET THE LEFT 2 DIGIT
SELECT NAME,PRODUCTNUMBER,LEFT(PRODUCTNUMBER,2) AS PRODUCT_TYPE
FROM SALESLT.PRODUCT

--GET THE RIGHT 2 DIGIT
SELECT NAME,PRODUCTNUMBER,RIGHT(PRODUCTNUMBER,2) AS PRODUCT_TYPE
FROM SALESLT.PRODUCT

SELECT NAME,PRODUCTNUMBER,RIGHT(PRODUCTNUMBER,2) AS PRODUCT_TYPE,
		SUBSTRING(PRODUCTNUMBER,CHARINDEX('-',PRODUCTNUMBER)+1,4) AS MODELCODE,
		SUBSTRING(PRODUCTNUMBER,LEN(PRODUCTNUMBER)-CHARINDEX('-',REVERSE(RIGHT(PRODUCTNUMBER,3)))+2,2) AS SIZECODE
FROM SALESLT.PRODUCT