--SUBQUERYS

--GET THE OVER PRICED PRODUCTS
SELECT * FROM SALESLT.PRODUCT
WHERE LISTPRICE >
(SELECT MAX(UNITPRICE) FROM SALESLT.SALESORDERDETAIL)

--CORELATED SUB QUERY
--Correlated subqueries reference objects in the outer query.
SELECT CUSTOMERID,SALESORDERID,ORDERDATE
FROM SALESLT.SALESORDER AS SO1
WHERE ORDERDATE=
(SELECT MAX(ORDERDATE) FROM SALESLT.SALESORDER AS SO2
WHERE SO2.CUSTOMERID=SO1.CUSTOMERID)
ORDER BY CUSTOMERID,ORDERDATE

