USE [ADVENTUREWORKSLT]

SELECT NAME,COLOR,SIZE FROM SALESLT.PRODUCT WHERE PRODUCTMODELID=6
SELECT NAME,COLOR,SIZE FROM SALESLT.PRODUCT WHERE PRODUCTMODELID>6

SELECT PRODUCTNUMBER,NAME,LISTPRICE FROM SALESLT.PRODUCT WHERE PRODUCTNUMBER LIKE 'FR%'

SELECT PRODUCTNUMBER,NAME,LISTPRICE FROM SALESLT.PRODUCT WHERE PRODUCTNUMBER LIKE 'FR-_[0-9][0-9]_-[0-9][0-5]'

SELECT NAME,LISTPRICE FROM SALESLT.PRODUCT WHERE SELLENDDATE IS  NOT NULL

SELECT NAME,LISTPRICE FROM SALESLT.PRODUCT WHERE SELLENDDATE BETWEEN '2006/1/1' AND '2006/12/31'

SELECT PRODUCTCATEGORYID,NAME,LISTPRICE FROM SALESLT.PRODUCT WHERE PRODUCTCATEGORYID IN (5,6,7)

SELECT PRODUCTCATEGORYID,PRODUCTNUMBER,NAME,LISTPRICE FROM SALESLT.PRODUCT WHERE PRODUCTCATEGORYID IN (5,6,7) OR PRODUCTNUMBER LIKE 'FR%'




